// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calc_mrf_logC_cpp
Rcpp::NumericVector calc_mrf_logC_cpp(const arma::mat& Theta, const Rcpp::NumericVector& nu);
RcppExport SEXP _multiGGM_calc_mrf_logC_cpp(SEXP ThetaSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_mrf_logC_cpp(Theta, nu));
    return rcpp_result_gen;
END_RCPP
}
// wishrnd_cpp
arma::mat wishrnd_cpp(const arma::mat& Sigma, double df);
RcppExport SEXP _multiGGM_wishrnd_cpp(SEXP SigmaSEXP, SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< double >::type df(dfSEXP);
    rcpp_result_gen = Rcpp::wrap(wishrnd_cpp(Sigma, df));
    return rcpp_result_gen;
END_RCPP
}
// log_iwishart_invA_const_cpp
double log_iwishart_invA_const_cpp(double df, const arma::mat& S);
RcppExport SEXP _multiGGM_log_iwishart_invA_const_cpp(SEXP dfSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type df(dfSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(log_iwishart_invA_const_cpp(df, S));
    return rcpp_result_gen;
END_RCPP
}
// log_J_cpp
double log_J_cpp(double h, const arma::mat& B, double a11);
RcppExport SEXP _multiGGM_log_J_cpp(SEXP hSEXP, SEXP BSEXP, SEXP a11SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type a11(a11SEXP);
    rcpp_result_gen = Rcpp::wrap(log_J_cpp(h, B, a11));
    return rcpp_result_gen;
END_RCPP
}
// log_H_cpp
double log_H_cpp(double b_prior, const arma::mat& D_prior, double n, const arma::mat& S, const arma::mat& C, int i, int j);
RcppExport SEXP _multiGGM_log_H_cpp(SEXP b_priorSEXP, SEXP D_priorSEXP, SEXP nSEXP, SEXP SSEXP, SEXP CSEXP, SEXP iSEXP, SEXP jSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type b_prior(b_priorSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type D_prior(D_priorSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C(CSEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    rcpp_result_gen = Rcpp::wrap(log_H_cpp(b_prior, D_prior, n, S, C, i, j));
    return rcpp_result_gen;
END_RCPP
}
// log_GWishart_NOij_pdf_cpp
double log_GWishart_NOij_pdf_cpp(double b_prior, const arma::mat& D_prior, arma::mat C, int i, int j, int edgeij);
RcppExport SEXP _multiGGM_log_GWishart_NOij_pdf_cpp(SEXP b_priorSEXP, SEXP D_priorSEXP, SEXP CSEXP, SEXP iSEXP, SEXP jSEXP, SEXP edgeijSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type b_prior(b_priorSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type D_prior(D_priorSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type C(CSEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    Rcpp::traits::input_parameter< int >::type edgeij(edgeijSEXP);
    rcpp_result_gen = Rcpp::wrap(log_GWishart_NOij_pdf_cpp(b_prior, D_prior, C, i, j, edgeij));
    return rcpp_result_gen;
END_RCPP
}
// maximal_cliques_cpp
arma::umat maximal_cliques_cpp(const arma::umat& adj0);
RcppExport SEXP _multiGGM_maximal_cliques_cpp(SEXP adj0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::umat& >::type adj0(adj0SEXP);
    rcpp_result_gen = Rcpp::wrap(maximal_cliques_cpp(adj0));
    return rcpp_result_gen;
END_RCPP
}
// GWishart_BIPS_maximumClique_cpp
Rcpp::List GWishart_BIPS_maximumClique_cpp(double bG, const arma::mat& DG, const arma::umat& adj, arma::mat C, int burnin, int nmc);
RcppExport SEXP _multiGGM_GWishart_BIPS_maximumClique_cpp(SEXP bGSEXP, SEXP DGSEXP, SEXP adjSEXP, SEXP CSEXP, SEXP burninSEXP, SEXP nmcSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type bG(bGSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type DG(DGSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type adj(adjSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type C(CSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< int >::type nmc(nmcSEXP);
    rcpp_result_gen = Rcpp::wrap(GWishart_BIPS_maximumClique_cpp(bG, DG, adj, C, burnin, nmc));
    return rcpp_result_gen;
END_RCPP
}
// GWishart_NOij_Gibbs_cpp
Rcpp::List GWishart_NOij_Gibbs_cpp(double bG, const arma::mat& DG, arma::umat adj, arma::mat C, int i, int j, int edgeij, int burnin, int nmc);
RcppExport SEXP _multiGGM_GWishart_NOij_Gibbs_cpp(SEXP bGSEXP, SEXP DGSEXP, SEXP adjSEXP, SEXP CSEXP, SEXP iSEXP, SEXP jSEXP, SEXP edgeijSEXP, SEXP burninSEXP, SEXP nmcSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type bG(bGSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type DG(DGSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type adj(adjSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type C(CSEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    Rcpp::traits::input_parameter< int >::type edgeij(edgeijSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< int >::type nmc(nmcSEXP);
    rcpp_result_gen = Rcpp::wrap(GWishart_NOij_Gibbs_cpp(bG, DG, adj, C, i, j, edgeij, burnin, nmc));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_multiGGM_calc_mrf_logC_cpp", (DL_FUNC) &_multiGGM_calc_mrf_logC_cpp, 2},
    {"_multiGGM_wishrnd_cpp", (DL_FUNC) &_multiGGM_wishrnd_cpp, 2},
    {"_multiGGM_log_iwishart_invA_const_cpp", (DL_FUNC) &_multiGGM_log_iwishart_invA_const_cpp, 2},
    {"_multiGGM_log_J_cpp", (DL_FUNC) &_multiGGM_log_J_cpp, 3},
    {"_multiGGM_log_H_cpp", (DL_FUNC) &_multiGGM_log_H_cpp, 7},
    {"_multiGGM_log_GWishart_NOij_pdf_cpp", (DL_FUNC) &_multiGGM_log_GWishart_NOij_pdf_cpp, 6},
    {"_multiGGM_maximal_cliques_cpp", (DL_FUNC) &_multiGGM_maximal_cliques_cpp, 1},
    {"_multiGGM_GWishart_BIPS_maximumClique_cpp", (DL_FUNC) &_multiGGM_GWishart_BIPS_maximumClique_cpp, 6},
    {"_multiGGM_GWishart_NOij_Gibbs_cpp", (DL_FUNC) &_multiGGM_GWishart_NOij_Gibbs_cpp, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_multiGGM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
