// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calc_mrf_logC_cpp
Rcpp::NumericVector calc_mrf_logC_cpp(const arma::mat& Theta, const Rcpp::NumericVector& nu);
RcppExport SEXP _multiGGM_calc_mrf_logC_cpp(SEXP ThetaSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_mrf_logC_cpp(Theta, nu));
    return rcpp_result_gen;
END_RCPP
}
// mcmc_engine_cpp
Rcpp::List mcmc_engine_cpp(Rcpp::List S_list_r, Rcpp::NumericVector n_vec_r, int burnin, int nsave, int thin, double b_prior, Rcpp::NumericMatrix D_prior_r, double a, double b_beta, double alpha, double beta_rate, double w_prior, double alpha_prop, double beta_prop, double a_prop, double b_prop, Rcpp::NumericMatrix Theta_init_r, Rcpp::NumericMatrix nu_init_r, Rcpp::NumericVector C_init_r, bool verbose, int print_every);
RcppExport SEXP _multiGGM_mcmc_engine_cpp(SEXP S_list_rSEXP, SEXP n_vec_rSEXP, SEXP burninSEXP, SEXP nsaveSEXP, SEXP thinSEXP, SEXP b_priorSEXP, SEXP D_prior_rSEXP, SEXP aSEXP, SEXP b_betaSEXP, SEXP alphaSEXP, SEXP beta_rateSEXP, SEXP w_priorSEXP, SEXP alpha_propSEXP, SEXP beta_propSEXP, SEXP a_propSEXP, SEXP b_propSEXP, SEXP Theta_init_rSEXP, SEXP nu_init_rSEXP, SEXP C_init_rSEXP, SEXP verboseSEXP, SEXP print_everySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type S_list_r(S_list_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type n_vec_r(n_vec_rSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< int >::type nsave(nsaveSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< double >::type b_prior(b_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type D_prior_r(D_prior_rSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b_beta(b_betaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta_rate(beta_rateSEXP);
    Rcpp::traits::input_parameter< double >::type w_prior(w_priorSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_prop(alpha_propSEXP);
    Rcpp::traits::input_parameter< double >::type beta_prop(beta_propSEXP);
    Rcpp::traits::input_parameter< double >::type a_prop(a_propSEXP);
    Rcpp::traits::input_parameter< double >::type b_prop(b_propSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Theta_init_r(Theta_init_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type nu_init_r(nu_init_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type C_init_r(C_init_rSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type print_every(print_everySEXP);
    rcpp_result_gen = Rcpp::wrap(mcmc_engine_cpp(S_list_r, n_vec_r, burnin, nsave, thin, b_prior, D_prior_r, a, b_beta, alpha, beta_rate, w_prior, alpha_prop, beta_prop, a_prop, b_prop, Theta_init_r, nu_init_r, C_init_r, verbose, print_every));
    return rcpp_result_gen;
END_RCPP
}
// mcmc_ssvs_engine_cpp
Rcpp::List mcmc_ssvs_engine_cpp(Rcpp::List S_list_r, Rcpp::NumericVector n_vec_r, int burnin, int nsave, int thin, double v0, double v1, double lambda_param, double a, double b_beta, double alpha, double beta_rate, double w_prior, double alpha_prop, double beta_prop, double a_prop, double b_prop, Rcpp::NumericMatrix Theta_init_r, Rcpp::NumericMatrix nu_init_r, Rcpp::NumericVector C_init_r, Rcpp::NumericVector Sig_init_r, bool verbose, int print_every);
RcppExport SEXP _multiGGM_mcmc_ssvs_engine_cpp(SEXP S_list_rSEXP, SEXP n_vec_rSEXP, SEXP burninSEXP, SEXP nsaveSEXP, SEXP thinSEXP, SEXP v0SEXP, SEXP v1SEXP, SEXP lambda_paramSEXP, SEXP aSEXP, SEXP b_betaSEXP, SEXP alphaSEXP, SEXP beta_rateSEXP, SEXP w_priorSEXP, SEXP alpha_propSEXP, SEXP beta_propSEXP, SEXP a_propSEXP, SEXP b_propSEXP, SEXP Theta_init_rSEXP, SEXP nu_init_rSEXP, SEXP C_init_rSEXP, SEXP Sig_init_rSEXP, SEXP verboseSEXP, SEXP print_everySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type S_list_r(S_list_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type n_vec_r(n_vec_rSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< int >::type nsave(nsaveSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    Rcpp::traits::input_parameter< double >::type v1(v1SEXP);
    Rcpp::traits::input_parameter< double >::type lambda_param(lambda_paramSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b_beta(b_betaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta_rate(beta_rateSEXP);
    Rcpp::traits::input_parameter< double >::type w_prior(w_priorSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_prop(alpha_propSEXP);
    Rcpp::traits::input_parameter< double >::type beta_prop(beta_propSEXP);
    Rcpp::traits::input_parameter< double >::type a_prop(a_propSEXP);
    Rcpp::traits::input_parameter< double >::type b_prop(b_propSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Theta_init_r(Theta_init_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type nu_init_r(nu_init_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type C_init_r(C_init_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Sig_init_r(Sig_init_rSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type print_every(print_everySEXP);
    rcpp_result_gen = Rcpp::wrap(mcmc_ssvs_engine_cpp(S_list_r, n_vec_r, burnin, nsave, thin, v0, v1, lambda_param, a, b_beta, alpha, beta_rate, w_prior, alpha_prop, beta_prop, a_prop, b_prop, Theta_init_r, nu_init_r, C_init_r, Sig_init_r, verbose, print_every));
    return rcpp_result_gen;
END_RCPP
}
// mcmc_ssvs_platform_engine_cpp
Rcpp::List mcmc_ssvs_platform_engine_cpp(Rcpp::List platform_S_lists, Rcpp::List platform_n_vecs, Rcpp::IntegerVector p_vec_r, int K, int burnin, int nsave, int thin, double v0, double v1, double lambda_param, double a, double b_beta, double alpha, double beta_rate, double w_prior, double alpha_prop, double beta_prop, double a_prop, double b_prop, double eta, double kappa, double eta_prop, double kappa_prop, double d_plat, double f_plat, double d_prop, double f_prop, double u_prior, Rcpp::List Theta_init_list, Rcpp::List nu_init_list, Rcpp::List C_init_list, Rcpp::List Sig_init_list, Rcpp::NumericMatrix Phi_init_r, Rcpp::NumericMatrix w_init_r, bool verbose, int print_every);
RcppExport SEXP _multiGGM_mcmc_ssvs_platform_engine_cpp(SEXP platform_S_listsSEXP, SEXP platform_n_vecsSEXP, SEXP p_vec_rSEXP, SEXP KSEXP, SEXP burninSEXP, SEXP nsaveSEXP, SEXP thinSEXP, SEXP v0SEXP, SEXP v1SEXP, SEXP lambda_paramSEXP, SEXP aSEXP, SEXP b_betaSEXP, SEXP alphaSEXP, SEXP beta_rateSEXP, SEXP w_priorSEXP, SEXP alpha_propSEXP, SEXP beta_propSEXP, SEXP a_propSEXP, SEXP b_propSEXP, SEXP etaSEXP, SEXP kappaSEXP, SEXP eta_propSEXP, SEXP kappa_propSEXP, SEXP d_platSEXP, SEXP f_platSEXP, SEXP d_propSEXP, SEXP f_propSEXP, SEXP u_priorSEXP, SEXP Theta_init_listSEXP, SEXP nu_init_listSEXP, SEXP C_init_listSEXP, SEXP Sig_init_listSEXP, SEXP Phi_init_rSEXP, SEXP w_init_rSEXP, SEXP verboseSEXP, SEXP print_everySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type platform_S_lists(platform_S_listsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type platform_n_vecs(platform_n_vecsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type p_vec_r(p_vec_rSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< int >::type nsave(nsaveSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< double >::type v0(v0SEXP);
    Rcpp::traits::input_parameter< double >::type v1(v1SEXP);
    Rcpp::traits::input_parameter< double >::type lambda_param(lambda_paramSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b_beta(b_betaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta_rate(beta_rateSEXP);
    Rcpp::traits::input_parameter< double >::type w_prior(w_priorSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_prop(alpha_propSEXP);
    Rcpp::traits::input_parameter< double >::type beta_prop(beta_propSEXP);
    Rcpp::traits::input_parameter< double >::type a_prop(a_propSEXP);
    Rcpp::traits::input_parameter< double >::type b_prop(b_propSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< double >::type eta_prop(eta_propSEXP);
    Rcpp::traits::input_parameter< double >::type kappa_prop(kappa_propSEXP);
    Rcpp::traits::input_parameter< double >::type d_plat(d_platSEXP);
    Rcpp::traits::input_parameter< double >::type f_plat(f_platSEXP);
    Rcpp::traits::input_parameter< double >::type d_prop(d_propSEXP);
    Rcpp::traits::input_parameter< double >::type f_prop(f_propSEXP);
    Rcpp::traits::input_parameter< double >::type u_prior(u_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type Theta_init_list(Theta_init_listSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type nu_init_list(nu_init_listSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type C_init_list(C_init_listSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type Sig_init_list(Sig_init_listSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Phi_init_r(Phi_init_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type w_init_r(w_init_rSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type print_every(print_everySEXP);
    rcpp_result_gen = Rcpp::wrap(mcmc_ssvs_platform_engine_cpp(platform_S_lists, platform_n_vecs, p_vec_r, K, burnin, nsave, thin, v0, v1, lambda_param, a, b_beta, alpha, beta_rate, w_prior, alpha_prop, beta_prop, a_prop, b_prop, eta, kappa, eta_prop, kappa_prop, d_plat, f_plat, d_prop, f_prop, u_prior, Theta_init_list, nu_init_list, C_init_list, Sig_init_list, Phi_init_r, w_init_r, verbose, print_every));
    return rcpp_result_gen;
END_RCPP
}
// wishrnd_cpp
arma::mat wishrnd_cpp(const arma::mat& Sigma, double df);
RcppExport SEXP _multiGGM_wishrnd_cpp(SEXP SigmaSEXP, SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< double >::type df(dfSEXP);
    rcpp_result_gen = Rcpp::wrap(wishrnd_cpp(Sigma, df));
    return rcpp_result_gen;
END_RCPP
}
// log_iwishart_invA_const_cpp
double log_iwishart_invA_const_cpp(double df, const arma::mat& S);
RcppExport SEXP _multiGGM_log_iwishart_invA_const_cpp(SEXP dfSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type df(dfSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(log_iwishart_invA_const_cpp(df, S));
    return rcpp_result_gen;
END_RCPP
}
// log_J_cpp
double log_J_cpp(double h, const arma::mat& B, double a11);
RcppExport SEXP _multiGGM_log_J_cpp(SEXP hSEXP, SEXP BSEXP, SEXP a11SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type a11(a11SEXP);
    rcpp_result_gen = Rcpp::wrap(log_J_cpp(h, B, a11));
    return rcpp_result_gen;
END_RCPP
}
// log_H_cpp
double log_H_cpp(double b_prior, const arma::mat& D_prior, double n, const arma::mat& S, const arma::mat& C, int i, int j);
RcppExport SEXP _multiGGM_log_H_cpp(SEXP b_priorSEXP, SEXP D_priorSEXP, SEXP nSEXP, SEXP SSEXP, SEXP CSEXP, SEXP iSEXP, SEXP jSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type b_prior(b_priorSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type D_prior(D_priorSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C(CSEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    rcpp_result_gen = Rcpp::wrap(log_H_cpp(b_prior, D_prior, n, S, C, i, j));
    return rcpp_result_gen;
END_RCPP
}
// log_GWishart_NOij_pdf_cpp
double log_GWishart_NOij_pdf_cpp(double b_prior, const arma::mat& D_prior, arma::mat C, int i, int j, int edgeij);
RcppExport SEXP _multiGGM_log_GWishart_NOij_pdf_cpp(SEXP b_priorSEXP, SEXP D_priorSEXP, SEXP CSEXP, SEXP iSEXP, SEXP jSEXP, SEXP edgeijSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type b_prior(b_priorSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type D_prior(D_priorSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type C(CSEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    Rcpp::traits::input_parameter< int >::type edgeij(edgeijSEXP);
    rcpp_result_gen = Rcpp::wrap(log_GWishart_NOij_pdf_cpp(b_prior, D_prior, C, i, j, edgeij));
    return rcpp_result_gen;
END_RCPP
}
// maximal_cliques_cpp
arma::umat maximal_cliques_cpp(const arma::umat& adj0);
RcppExport SEXP _multiGGM_maximal_cliques_cpp(SEXP adj0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::umat& >::type adj0(adj0SEXP);
    rcpp_result_gen = Rcpp::wrap(maximal_cliques_cpp(adj0));
    return rcpp_result_gen;
END_RCPP
}
// GWishart_BIPS_maximumClique_cpp
Rcpp::List GWishart_BIPS_maximumClique_cpp(double bG, const arma::mat& DG, const arma::umat& adj, arma::mat C, int burnin, int nmc);
RcppExport SEXP _multiGGM_GWishart_BIPS_maximumClique_cpp(SEXP bGSEXP, SEXP DGSEXP, SEXP adjSEXP, SEXP CSEXP, SEXP burninSEXP, SEXP nmcSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type bG(bGSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type DG(DGSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type adj(adjSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type C(CSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< int >::type nmc(nmcSEXP);
    rcpp_result_gen = Rcpp::wrap(GWishart_BIPS_maximumClique_cpp(bG, DG, adj, C, burnin, nmc));
    return rcpp_result_gen;
END_RCPP
}
// GWishart_NOij_Gibbs_cpp
Rcpp::List GWishart_NOij_Gibbs_cpp(double bG, const arma::mat& DG, arma::umat adj, arma::mat C, int i, int j, int edgeij, int burnin, int nmc);
RcppExport SEXP _multiGGM_GWishart_NOij_Gibbs_cpp(SEXP bGSEXP, SEXP DGSEXP, SEXP adjSEXP, SEXP CSEXP, SEXP iSEXP, SEXP jSEXP, SEXP edgeijSEXP, SEXP burninSEXP, SEXP nmcSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type bG(bGSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type DG(DGSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type adj(adjSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type C(CSEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    Rcpp::traits::input_parameter< int >::type edgeij(edgeijSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< int >::type nmc(nmcSEXP);
    rcpp_result_gen = Rcpp::wrap(GWishart_NOij_Gibbs_cpp(bG, DG, adj, C, i, j, edgeij, burnin, nmc));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_multiGGM_calc_mrf_logC_cpp", (DL_FUNC) &_multiGGM_calc_mrf_logC_cpp, 2},
    {"_multiGGM_mcmc_engine_cpp", (DL_FUNC) &_multiGGM_mcmc_engine_cpp, 21},
    {"_multiGGM_mcmc_ssvs_engine_cpp", (DL_FUNC) &_multiGGM_mcmc_ssvs_engine_cpp, 23},
    {"_multiGGM_mcmc_ssvs_platform_engine_cpp", (DL_FUNC) &_multiGGM_mcmc_ssvs_platform_engine_cpp, 36},
    {"_multiGGM_wishrnd_cpp", (DL_FUNC) &_multiGGM_wishrnd_cpp, 2},
    {"_multiGGM_log_iwishart_invA_const_cpp", (DL_FUNC) &_multiGGM_log_iwishart_invA_const_cpp, 2},
    {"_multiGGM_log_J_cpp", (DL_FUNC) &_multiGGM_log_J_cpp, 3},
    {"_multiGGM_log_H_cpp", (DL_FUNC) &_multiGGM_log_H_cpp, 7},
    {"_multiGGM_log_GWishart_NOij_pdf_cpp", (DL_FUNC) &_multiGGM_log_GWishart_NOij_pdf_cpp, 6},
    {"_multiGGM_maximal_cliques_cpp", (DL_FUNC) &_multiGGM_maximal_cliques_cpp, 1},
    {"_multiGGM_GWishart_BIPS_maximumClique_cpp", (DL_FUNC) &_multiGGM_GWishart_BIPS_maximumClique_cpp, 6},
    {"_multiGGM_GWishart_NOij_Gibbs_cpp", (DL_FUNC) &_multiGGM_GWishart_NOij_Gibbs_cpp, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_multiGGM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
