# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute log normalizing constant for the edge-sharing MRF prior
#'
#' Computes \eqn{\log C(\Theta, \nu)} where
#' \deqn{C(\Theta,\nu)=\sum_{g\in\{0,1\}^K} \exp\{\nu \mathbf{1}^\top g + g^\top \Theta g\}.}
#'
#' @param Theta A K x K symmetric matrix.
#' @param nu Numeric vector of length 1 or more.
#' @return Numeric vector of \eqn{\log C(\Theta,\nu)} for each entry of \code{nu}.
#' @export
calc_mrf_logC_cpp <- function(Theta, nu) {
    .Call(`_multiGGM_calc_mrf_logC_cpp`, Theta, nu)
}

mcmc_engine_cpp <- function(S_list_r, n_vec_r, burnin, nsave, thin, b_prior, D_prior_r, a, b_beta, alpha, beta_rate, w_prior, alpha_prop, beta_prop, a_prop, b_prop, Theta_init_r, nu_init_r, C_init_r, verbose, print_every) {
    .Call(`_multiGGM_mcmc_engine_cpp`, S_list_r, n_vec_r, burnin, nsave, thin, b_prior, D_prior_r, a, b_beta, alpha, beta_rate, w_prior, alpha_prop, beta_prop, a_prop, b_prop, Theta_init_r, nu_init_r, C_init_r, verbose, print_every)
}

mcmc_ssvs_engine_cpp <- function(S_list_r, n_vec_r, burnin, nsave, thin, v0, v1, lambda_param, a, b_beta, alpha, beta_rate, w_prior, alpha_prop, beta_prop, a_prop, b_prop, Theta_init_r, nu_init_r, C_init_r, Sig_init_r, verbose, print_every) {
    .Call(`_multiGGM_mcmc_ssvs_engine_cpp`, S_list_r, n_vec_r, burnin, nsave, thin, v0, v1, lambda_param, a, b_beta, alpha, beta_rate, w_prior, alpha_prop, beta_prop, a_prop, b_prop, Theta_init_r, nu_init_r, C_init_r, Sig_init_r, verbose, print_every)
}

mcmc_ssvs_platform_engine_cpp <- function(platform_S_lists, platform_n_vecs, p_vec_r, K, burnin, nsave, thin, v0, v1, lambda_param, a, b_beta, alpha, beta_rate, w_prior, alpha_prop, beta_prop, a_prop, b_prop, eta, kappa, eta_prop, kappa_prop, d_plat, f_plat, d_prop, f_prop, u_prior, Theta_init_list, nu_init_list, C_init_list, Sig_init_list, Phi_init_r, w_init_r, verbose, print_every) {
    .Call(`_multiGGM_mcmc_ssvs_platform_engine_cpp`, platform_S_lists, platform_n_vecs, p_vec_r, K, burnin, nsave, thin, v0, v1, lambda_param, a, b_beta, alpha, beta_rate, w_prior, alpha_prop, beta_prop, a_prop, b_prop, eta, kappa, eta_prop, kappa_prop, d_plat, f_plat, d_prop, f_prop, u_prior, Theta_init_list, nu_init_list, C_init_list, Sig_init_list, Phi_init_r, w_init_r, verbose, print_every)
}

wishrnd_cpp <- function(Sigma, df) {
    .Call(`_multiGGM_wishrnd_cpp`, Sigma, df)
}

log_iwishart_invA_const_cpp <- function(df, S) {
    .Call(`_multiGGM_log_iwishart_invA_const_cpp`, df, S)
}

log_J_cpp <- function(h, B, a11) {
    .Call(`_multiGGM_log_J_cpp`, h, B, a11)
}

log_H_cpp <- function(b_prior, D_prior, n, S, C, i, j) {
    .Call(`_multiGGM_log_H_cpp`, b_prior, D_prior, n, S, C, i, j)
}

log_GWishart_NOij_pdf_cpp <- function(b_prior, D_prior, C, i, j, edgeij) {
    .Call(`_multiGGM_log_GWishart_NOij_pdf_cpp`, b_prior, D_prior, C, i, j, edgeij)
}

maximal_cliques_cpp <- function(adj0) {
    .Call(`_multiGGM_maximal_cliques_cpp`, adj0)
}

GWishart_BIPS_maximumClique_cpp <- function(bG, DG, adj, C, burnin, nmc) {
    .Call(`_multiGGM_GWishart_BIPS_maximumClique_cpp`, bG, DG, adj, C, burnin, nmc)
}

GWishart_NOij_Gibbs_cpp <- function(bG, DG, adj, C, i, j, edgeij, burnin, nmc) {
    .Call(`_multiGGM_GWishart_NOij_Gibbs_cpp`, bG, DG, adj, C, i, j, edgeij, burnin, nmc)
}

