# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute log normalizing constant for the edge-sharing MRF prior
#'
#' Computes \eqn{\log C(\Theta, \nu)} where
#' \deqn{C(\Theta,\nu)=\sum_{g\in\{0,1\}^K} \exp\{\nu \mathbf{1}^\top g + g^\top \Theta g\}.}
#'
#' @param Theta A K x K symmetric matrix.
#' @param nu Numeric vector of length 1 or more.
#' @return Numeric vector of \eqn{\log C(\Theta,\nu)} for each entry of \code{nu}.
#' @export
calc_mrf_logC_cpp <- function(Theta, nu) {
    .Call(`_multiGGM_calc_mrf_logC_cpp`, Theta, nu)
}

wishrnd_cpp <- function(Sigma, df) {
    .Call(`_multiGGM_wishrnd_cpp`, Sigma, df)
}

log_iwishart_invA_const_cpp <- function(df, S) {
    .Call(`_multiGGM_log_iwishart_invA_const_cpp`, df, S)
}

log_J_cpp <- function(h, B, a11) {
    .Call(`_multiGGM_log_J_cpp`, h, B, a11)
}

log_H_cpp <- function(b_prior, D_prior, n, S, C, i, j) {
    .Call(`_multiGGM_log_H_cpp`, b_prior, D_prior, n, S, C, i, j)
}

log_GWishart_NOij_pdf_cpp <- function(b_prior, D_prior, C, i, j, edgeij) {
    .Call(`_multiGGM_log_GWishart_NOij_pdf_cpp`, b_prior, D_prior, C, i, j, edgeij)
}

maximal_cliques_cpp <- function(adj0) {
    .Call(`_multiGGM_maximal_cliques_cpp`, adj0)
}

GWishart_BIPS_maximumClique_cpp <- function(bG, DG, adj, C, burnin, nmc) {
    .Call(`_multiGGM_GWishart_BIPS_maximumClique_cpp`, bG, DG, adj, C, burnin, nmc)
}

GWishart_NOij_Gibbs_cpp <- function(bG, DG, adj, C, i, j, edgeij, burnin, nmc) {
    .Call(`_multiGGM_GWishart_NOij_Gibbs_cpp`, bG, DG, adj, C, i, j, edgeij, burnin, nmc)
}

